apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostel-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hostel
  template:
    metadata:
      labels:
        app: hostel
    spec:
      containers:
      - name: hostel-web
        image: REPLACE_LATER_BY_GITHUB_ACTION
        ports:
          - containerPort: 5000
        env:
          - name: DB_HOST
            value: "hostel-db.default.svc.cluster.local"
          - name: DB_PORT
            value: "3306"
          - name: DB_NAME
            value: "hostel_db"
          - name: DB_USER
            value: "root"
          - name: DB_PASSWORD
            value: "admin@123"
